### ISSUE TITLE
How to handle Slack actions that take longer than 3 seconds

### ISSUE THREAD

**Issue by dck** [dempfi/xene#13]
Hello! 
According to the source code https://github.com/dempfi/xene/blob/master/packages/slack/src/middleware/middlewares.ts#L31

It calls a callback passing a context object, awaits it and then it compares the object message field with the original message and formats a response.

However, some handlers can take more than 3 seconds and Slack automatically marks them as failed. 
In theory, we are able to send 200 and some body (with ephemeral message for example), finish the job and update the original message later.

According to `MiddlewareContext ` interface it's not clear what we can use to achieve this. It expects only changes on `message` or `ephemeral` fields.

**Comment by dempfi** [comment]
Hear you, will fix in next release.

**Comment by dempfi** [comment]
Closed in [@xene/slack@0.1.16](https://github.com/dempfi/xene/releases/tag/%40xene%2Fslack%400.1.16)
